In [1]:
from google_play_scraper import app, reviews_all, Sort
import pandas as pd
import numpy as np

pd.options.mode.chained_assignment = None
seed = 0
np.random.seed(seed)

print('Library berhasil di-import!')

Library berhasil di-import!

In [2]:
scrapreview = reviews_all(
    'com.apps.MyXL',
    lang='id',
    country='id',
    sort=Sort.MOST_RELEVANT,
    count=1000
)

print(f'Berhasil scraping {len(scrapreview)} review')

Berhasil scraping 576000 review

In [3]:
# Konversi hasil scraping ke DataFrame
app_reviews_df = pd.DataFrame(scrapreview)

jumlah_ulasan, jumlah_kolom = app_reviews_df.shape
print(f'Jumlah ulasan: {jumlah_ulasan}')
print(f'Jumlah kolom: {jumlah_kolom}')
print()

app_reviews_df.head()

Jumlah ulasan: 576000
Jumlah kolom: 11

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,52a9ccff-a3d9-41a3-8b3e-45da1d784743,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Semakin jelek kualitas jaringan XL, tiba"" sign...",1,387,9.5.0,2026-09-17 01:03:57,"Hi Kak, mohon maaf ya atas ketidaknyamanan yan...",2026-09-17 02:00:14,9.5.0
1,df316426-9c94-440e-a0c3-470e94bdd10b,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Aplikasi banyak bug, tidak stabil, sering eror...",1,69,9.5.0,2026-09-11 05:36:50,"Hi Kak, maaf ya, agar dapat dibantu cek lebih ...",2026-09-11 06:00:08,9.5.0
2,a94ab251-1eed-44d0-b6fe-ef7209c6f44d,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,⭐ 1/5 “Sering mengalami gangguan saat membeli ...,1,60,9.5.0,2026-09-09 17:45:59,"Hi Kak, mohon maaf ya atas ketidaknyamanan yan...",2026-09-09 18:00:13,9.5.0
3,a88fe295-18ae-4bad-8be1-536092dc9ad1,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Saya ubah penilaian saya karena sekarang ini a...,1,57,9.5.0,2026-09-14 08:26:40,"Hi Kak, mohon maaf ya atas kendalanya. Yuk hub...",2023-12-04 08:04:00,9.5.0
4,a8825f6d-ff7c-4817-9f54-0581455eca3f,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Sudah dua kali beli paket flexmini. Yang perta...,1,49,9.5.0,2026-09-09 17:36:08,"Hi Kak, mohon maaf ya atas ketidaknyamanan yan...",2026-09-09 18:00:17,9.5.0

In [4]:
# Cek duplikat sebelum dihapus
jumlah_duplikat = app_reviews_df.duplicated().sum()
print(f'Jumlah data duplikat: {jumlah_duplikat}')

# Hapus duplikat
app_reviews_df = app_reviews_df.drop_duplicates()

jumlah_setelah, kolom_setelah = app_reviews_df.shape
print(f'Jumlah ulasan setelah hapus duplikat: {jumlah_setelah}')

Jumlah data duplikat: 0
Jumlah ulasan setelah hapus duplikat: 576000

In [5]:
# Simpan seluruh kolom ke CSV
app_reviews_df.to_csv('komen_XL.csv', index=False)

print(f'Data berhasil disimpan ke komen_XL.csv ({len(app_reviews_df)} baris)')
print(f'Kolom yang tersimpan: {list(app_reviews_df.columns)}')

Data berhasil disimpan ke komen_XL.csv (576000 baris)
Kolom yang tersimpan: ['reviewId', 'userName', 'userImage', 'content', 'score', 'thumbsUpCount', 'reviewCreatedVersion', 'at', 'replyContent', 'repliedAt', 'appVersion']

In [6]:
# Verifikasi: baca ulang CSV yang sudah disimpan
verify_df = pd.read_csv('komen_XL.csv')
print(f'Verifikasi - jumlah baris di CSV: {len(verify_df)}')
verify_df.head()

Verifikasi - jumlah baris di CSV: 576000

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,52a9ccff-a3d9-41a3-8b3e-45da1d784743,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Semakin jelek kualitas jaringan XL, tiba"" sign...",1,387,9.5.0,2026-09-17 01:03:57,"Hi Kak, mohon maaf ya atas ketidaknyamanan yan...",2026-09-17 02:00:14,9.5.0
1,df316426-9c94-440e-a0c3-470e94bdd10b,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Aplikasi banyak bug, tidak stabil, sering eror...",1,69,9.5.0,2026-09-11 05:36:50,"Hi Kak, maaf ya, agar dapat dibantu cek lebih ...",2026-09-11 06:00:08,9.5.0
2,a94ab251-1eed-44d0-b6fe-ef7209c6f44d,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,⭐ 1/5 “Sering mengalami gangguan saat membeli ...,1,60,9.5.0,2026-09-09 17:45:59,"Hi Kak, mohon maaf ya atas ketidaknyamanan yan...",2026-09-09 18:00:13,9.5.0
3,a88fe295-18ae-4bad-8be1-536092dc9ad1,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Saya ubah penilaian saya karena sekarang ini a...,1,57,9.5.0,2026-09-14 08:26:40,"Hi Kak, mohon maaf ya atas kendalanya. Yuk hub...",2023-12-04 08:04:00,9.5.0
4,a8825f6d-ff7c-4817-9f54-0581455eca3f,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Sudah dua kali beli paket flexmini. Yang perta...,1,49,9.5.0,2026-09-09 17:36:08,"Hi Kak, mohon maaf ya atas ketidaknyamanan yan...",2026-09-09 18:00:17,9.5.0